joy/theme/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url


from joy.theme.views import ListView, SongList, ArtistDetail, get_captions, SongOfTheDayList, AllArtistList, browse, SongDetail


urlpatterns = patterns("",
   url(r'^newest/$', SongList.as_view()),
   url(r'^artist/(?P<slug>[-_\w]+)/$', ArtistDetail.as_view(), name='artist_detail'),
   url(r'^song/(?P<slug>[-_\w]+)/$', SongDetail.as_view(), name='song_detail'),
   url(r'^services/(?P<song_id>[0-9]+)/$', get_captions, name='get_captions'),
   url(r'^sotd/$', SongOfTheDayList.as_view(), name='songoftheday_listing'),
   url(r'^artists/$', AllArtistList.as_view(), name='get_artists'),
   url(r'^browse/$', browse, name='browse'),
)

joy/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

urlpatterns += patterns('',

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

     #url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),
    ("^", include("joy.theme.urls")),
    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

joy/theme/models.py
from django.db import models
from mezzanine.core.fields import RichTextField

class Artist(models.Model):
    name = models.CharField(max_length=200)
    album = models.ManyToManyField("Album", related_name="Album", blank=True, null=True)
    web_site = models.CharField(max_length=200, blank=True, null=True)
    twitter_handle = models.CharField(max_length=100, blank=True, null=True)
    facebook = models.CharField(max_length=200, blank=True, null=True)
    pinterest = models.CharField(max_length=200, blank=True, null=True)
    google = models.CharField(max_length=200, blank=True, null=True)
    youtube = models.CharField(max_length=200, blank=True, null=True)
    vimeo = models.CharField(max_length=200, blank=True, null=True)
    content = RichTextField(("Content"), blank=True, null=True)
    slug = models.SlugField(max_length=400)

    def __unicode__(self):
        return self.name

class Song(models.Model):
    name = models.CharField(max_length=300)
    artist = models.ManyToManyField("Artist", related_name="Artist", blank=True, null=True)
    lyrics = models.TextField()
    captions = models.FileField(upload_to="captions", blank=True, null=True)
    content = RichTextField(("Content"), blank=True, null=True)
    video_content = models.CharField(max_length=200, blank=True, null=True)
    video_type = models.ForeignKey("VideoType", blank=True, null=True)
    slug = models.SlugField(max_length=400)
    audio = models.CharField(max_length=600, blank=True, null=True)
    itunes_url = models.CharField(max_length=800, blank=True, null=True)
    amazon_url = models.CharField(max_length=800, blank=True, null=True)
    google_url = models.CharField(max_length=800, blank=True, null=True)

    def __unicode__(self):
        return self.name


class Album(models.Model):
    name = models.CharField(max_length=200)
    song = models.ManyToManyField("Song", related_name="Song", blank=True, null=True)
    art = models.ImageField(upload_to="album_art")
    content = RichTextField(("Content"), blank=True)
    amazon_buy_url = models.CharField(max_length=800, blank=True, null=True)
    itunes_buy_url = models.CharField(max_length=800, blank=True, null=True)
    google_buy_url = models.CharField(max_length=800, blank=True, null=True)
    slug = models.SlugField(max_length=400)

    def __unicode__(self):
        return self.name

class VideoType(models.Model):
    video_type_id = models.SmallIntegerField()
    tech = models.CharField(max_length=200)

    def __unicode__(self):
        return u"%s" % (self.tech)

class SongOfTheDay(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField(("Content"), blank=True, null=True)
    song = models.ManyToManyField("Song", related_name="SongOfTheDaySong")
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.title

joy/theme/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.utils import simplejson
from django.utils.datetime_safe import date
from django.views.generic import ListView, CreateView, DetailView
from requests import request
from joy.theme.models import SongOfTheDay, Artist, Song
from joy.theme import joy_spider


class SongList(ListView):

    model = SongOfTheDay
    today = date.today()
    queryset = SongOfTheDay.objects.filter(pub_date__year=today.year, pub_date__month=today.month, pub_date__day=today.day)

class ArtistDetail(DetailView):
    model = Artist

    def get_context_data(self, **kwargs):
        context = super(ArtistDetail, self).get_context_data(**kwargs)
        #context['now'] = timezone.now()
        return context

class SongDetail(DetailView):
    model = Song

    def get_context_data(self, **kwargs):
        context = super(SongDetail, self).get_context_data(**kwargs)
        return context

class LinkDetail(DetailView):
    model = SongOfTheDay

class SongOfTheDayList(ListView):
    model = SongOfTheDay
    queryset = SongOfTheDay.objects.all()

class AllArtistList(ListView):
    model = Artist
    queryset = Artist.objects.all()

def get_captions(request, song_id):
    current_song = get_object_or_404(Song, pk=song_id)
    return HttpResponse(current_song.captions)

def browse(request):
    spider = joy_spider.JoySpider()
    return HttpResponse("Snappers")

joy/theme/templates/theme/artist_detail.html
{% extends "base.html" %}

{% load mezzanine_tags future %}

{% block meta_title %}{{ title|default:"Home" }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block main %}


<h1>{{ artist.name }}</h1>
<ul>
    {% for album in artist.album.all %}
        <li>{{ album.name }}</li>
        <ul>
            {% for song in album.song.all %}
                <li><a href="/song/{{ song.slug }}">{{ song.name }}</a></li>
            {% endfor %}
        </ul>
    {% endfor %}
</ul>

{% endblock %}

joy/theme/templates/theme/artist_list.html
{% extends "base.html" %}

{% load mezzanine_tags future %}

{% block meta_title %}{{ title|default:"Home" }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block main %}


    <h2>all artists</h2>
    <ul>
        {% for artist in object_list %}
            <li>{{ artist.name }}</li>

        {% endfor %}

    </ul>


{% endblock %}

joy/theme/templates/theme/song_detail.html
{% extends "base.html" %}

{% load mezzanine_tags future %}

{% block meta_title %}{{ title|default:"Home" }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block main %}


<h1>{{ song.name }}</h1>


{% endblock %}

joy/theme/templates/theme/song_list.html
{% extends "base.html" %}

{% load mezzanine_tags future %}

{% block meta_title %}{{ title|default:"Home" }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block main %}


    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.title }}</li>
        {% endfor %}
    </ul>




{% endblock %}

joy/theme/templates/theme/songoftheday_list.html
{% extends "base.html" %}

{% load mezzanine_tags future %}

{% block meta_title %}{{ title|default:"Home" }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block main %}



<h2>Publishers</h2>
<ul>
    {% for publisher in object_list %}
    <li>{{ publisher.song }}</li>


    {% for pop in publisher.song.all %}
    <strong>ID = {{ pop.video_type.video_type_id }} </strong>
    {% if pop.video_type.video_type_id == 0 %}
        <div id="viemo">
            <iframe id="player1" src="http://player.vimeo.com/video/{{ pop.video_content }}?api=1&player_id=player1" width="400" height="225"
            frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>

    {% else %}
        <div id="youtube" data-video="{{ pop.video_content }}">

            <div id="tuba"></div>
        </div>

    {% endif %}




    <div class="video" data-type="{% if pop.video_type.video_type_id == 0 %}viemo{% else %}youtube>{% endif %}">
            <strong>Viemo {{ pop.video_content }}</strong>


     </div>

    <div id="result"></div>

    <p> Song: {{ pop }} - {{ pop.content }}</p>

    <p>{{ pop.artist }}</p>

    <p>{{ pop.album.name }}</p>

    <p>{{ pop.id }} </p>

    {% for album in pop.album.all %}
    <li>{{ album.name }}</li>

    {% endfor %}


    <p>captions {{ pop.captions.name }}</p>

    <hr/>


    {% endfor %}


    {% endfor %}

    {% for artist in object_list.song_set.all %}
    <p>Artist: {{ artist }}</p>

    {% endfor %}

</ul>

<script id="tester" type="text/vtt"></script>





{% endblock %}

joy/theme/templates/theme/songoftheday_listing.html
{% extends "base.html" %}

{% load mezzanine_tags future %}

{% block meta_title %}{{ title|default:"Home" }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block main %}

    <iframe id="player1" src="http://player.vimeo.com/video/27855315?api=1&player_id=player1" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>



     <div id="result"></div>
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.song }}</li>


        {% for pop in publisher.song.all %}
            <p> Song: {{ pop }} - {{ pop.content }}</p>
            <p>{{ pop.artist }}</p>
            <p>{{ pop.album.name }}</p>
           <p>{{ pop.id }} </p>

        {% for album in pop.album.all %}
            <li>{{ album.name }}</li>

        {% endfor %}



            <p>captions {{ pop.captions.name }}</p>

            <hr/>

            {% if pop.video_type.video_type_id == 0 %}
                <p>Viemo {{ pop.video_content }}</p>
            {% else %}
                <p>youtube {{ pop.video_content }}</p>
            {% endif %}
        {% endfor %}



        {% endfor %}

            {% for artist in object_list.song_set.all %}
                <p>Artist: {{ artist }}</p>

            {% endfor %}

    </ul>


<script>
    var captions;
    var vimeoConfig;
    var vimeoPlayer;
    var scope = this;
    $( document ).ready(function() {
        //get captions
        $.ajax({
            url: "/services/1",
            cache: true,
            success: function(data){
                scope.setCaptions(data);
            }
        });
    });

    function setCaptions(captions){
        $("#tester").html(captions)
        //set player up:
        vimeoConfig =  {
            container: document.getElementById('player1')
        };
        vimeoPlayer = new Vimeo(vimeoConfig);

        vimeoConfig.container.addEventListener('onPlayerReady', function(e){
            vimeoPlayer.play();

        });

        vimeoConfig.container.addEventListener('onProgress', function(e){
         $('#tester').webVtt(formatSecondsAsTime(vimeoPlayer.getSeek())).appendTo('#result');

        });
    }

    function formatSecondsAsTime(secs, format) {
        var hr  = Math.floor(secs / 3600);
        var min = Math.floor((secs - (hr * 3600))/60);
        var sec = Math.floor(secs - (hr * 3600) -  (min * 60));

        if (hr < 10){ hr    = "0" + hr; }
        if (min < 10){ min = "0" + min; }
        if (sec < 10){ sec  = "0" + sec; }
        if (hr){ hr   = "00"; }

        return hr + ':' + min + ':' + sec + ".000";
    }

</script>
<script id="tester" type="text/vtt"></script>

{% endblock %}